#!/bin/bash
# Validation Report Generator
# Creates comprehensive test report

set -euo pipefail

echo "=== Generating Validation Report ==="
echo ""

REPORT_FILE="reports/validation-report-$(date +%Y%m%d-%H%M%S).md"

cat > "$REPORT_FILE" << REPORT
# ORCHAT Validation Report
## Phase 7.5 Hardening Sprint
### Generated: $(date)

## System Information
- Hostname: $(hostname)
- User: $(whoami)
- OS: $(uname -srm)
- Shell: $SHELL
- Date: $(date)

## Test Categories

### 1. Installation Tests
\`\`\`
$(cd install && ls -la *.sh 2>/dev/null | awk '{print $9}' || echo "No tests found")
\`\`\`

### 2. Runtime Tests
\`\`\`
$(cd runtime && ls -la *.sh 2>/dev/null | awk '{print $9}' || echo "No tests found")
\`\`\`

### 3. Performance Tests
\`\`\`
$(cd performance && ls -la *.sh 2>/dev/null | awk '{print $9}' || echo "No tests found")
\`\`\`

### 4. Observability Tests
\`\`\`
$(cd observability && ls -la *.sh 2>/dev/null | awk '{print $9}' || echo "No tests found")
\`\`\`

## API Key Status
\`\`\`
$(~/.config/orchat/secure_key.sh validate 2>/dev/null || echo "API Key: Not configured")
\`\`\`

## ORCHAT Version
\`\`\`
$(orchat --version 2>/dev/null || echo "Version check failed")
\`\`\`

## Recommendations
1. Run all validation tests: \`./run-all.sh\`
2. Review failing tests in \`reports/failure-log.md\`
3. Complete Phase 7.5 certification

---
*Report generated by ORCHAT Validation Framework*
REPORT

echo "✅ Report generated: $REPORT_FILE"
echo ""
echo "To view the report:"
echo "  cat $REPORT_FILE"
echo "  or"
echo "  less $REPORT_FILE"
